update my repo
Wolfsurge/Paragon pull request #23
Opened 2022-08-01 08:10 UTC by GentlemanMC

again (again)

2022-08-01 09:34 UTC, Wolfsurge requested changes

2022-08-01 09:34 UTC, Wolfsurge commented on src/main/java/com/paragon/client/systems/module/impl/misc/ChorusControl.java
> +    private final Setting<Boolean> cPacketPlayer = new Setting<>("cPacketPlayer", true);
Capital C for name arg

2022-08-01 09:34 UTC, Wolfsurge commented on src/main/java/com/paragon/client/systems/module/impl/misc/ChorusControl.java
> +    public void onPacketReceive(final PacketEvent.PreReceive event) {
Remove the final modifier, not needed (effectively final)

2022-08-01 09:34 UTC, Wolfsurge commented on src/main/java/com/paragon/client/systems/module/impl/misc/ChorusControl.java
> +    public void onRender3D() {
Move to above the onPacketReceive method

2022-08-01 09:34 UTC, Wolfsurge commented
also, have you tested this on servers?

2022-08-01 11:02 UTC, GentlemanMC commented
> also, have you tested this on servers?

yes

2022-08-02 12:36 UTC, SooStrator1136 commented on src/main/java/com/paragon/client/systems/module/impl/misc/ChorusControl.java
> +    public void onPacketReceive(final PacketEvent.PreReceive event) {
Not needed but good practise since you shouldn't modify a parameter, but ill change it ig

2022-08-02 12:41 UTC, SooStrator1136 commented on src/main/java/com/paragon/client/systems/module/impl/misc/ChorusControl.java
> +    public void onPacketReceive(final PacketEvent.PreReceive event) {
I didn't want to make it yet kt since I think gentle is better with java

2022-08-07 17:50 UTC, Wolfsurge approved these changes

2022-08-07 17:51 UTC, merged